import { ConnectWallet, useContract } from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { contractAbi, contractAddress } from "../contract";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { contract, isLoading } = useContract(contractAddress, contractAbi);
  const router = useRouter();

  const checkAndRedirect = async () => {
    try {
      const response = await fetch("/api/check");
      const data = response.json();
      console.log(response);
      if (!response.ok) return alert("Not eligible for access");
      router.push("/content");
    } catch (err) {
      console.error(err);
      alert("An error occured");
    }
  };

  const getTokens = async () => {
    try {
      if (isLoading) return;
      await contract.call("drip");
      alert("Tokens added!");
    } catch (err) {
      console.error(err);
      alert("An error occured");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button onClick={checkAndRedirect}>Check eligibility</button>
      </div>

      <div>
        <button onClick={getTokens}>Get tokens</button>
      </div>

      <div style={{ width: "200px" }}>
        <ConnectWallet />
      </div>
    </div>
  );
}
